/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RoadmapImport } from './routes/roadmap'
import { Route as FeaturesImport } from './routes/features'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as MarketplaceIndexImport } from './routes/marketplace/index'
import { Route as MarketplaceContractIdImport } from './routes/marketplace/$contractId'

// Create/Update Routes

const RoadmapRoute = RoadmapImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRoute,
} as any)

const FeaturesRoute = FeaturesImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MarketplaceIndexRoute = MarketplaceIndexImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRoute,
} as any)

const MarketplaceContractIdRoute = MarketplaceContractIdImport.update({
  id: '/marketplace/$contractId',
  path: '/marketplace/$contractId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesImport
      parentRoute: typeof rootRoute
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapImport
      parentRoute: typeof rootRoute
    }
    '/marketplace/$contractId': {
      id: '/marketplace/$contractId'
      path: '/marketplace/$contractId'
      fullPath: '/marketplace/$contractId'
      preLoaderRoute: typeof MarketplaceContractIdImport
      parentRoute: typeof rootRoute
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/roadmap': typeof RoadmapRoute
  '/marketplace/$contractId': typeof MarketplaceContractIdRoute
  '/marketplace': typeof MarketplaceIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/roadmap': typeof RoadmapRoute
  '/marketplace/$contractId': typeof MarketplaceContractIdRoute
  '/marketplace': typeof MarketplaceIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/roadmap': typeof RoadmapRoute
  '/marketplace/$contractId': typeof MarketplaceContractIdRoute
  '/marketplace/': typeof MarketplaceIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/features'
    | '/roadmap'
    | '/marketplace/$contractId'
    | '/marketplace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/features'
    | '/roadmap'
    | '/marketplace/$contractId'
    | '/marketplace'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/features'
    | '/roadmap'
    | '/marketplace/$contractId'
    | '/marketplace/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FeaturesRoute: typeof FeaturesRoute
  RoadmapRoute: typeof RoadmapRoute
  MarketplaceContractIdRoute: typeof MarketplaceContractIdRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FeaturesRoute: FeaturesRoute,
  RoadmapRoute: RoadmapRoute,
  MarketplaceContractIdRoute: MarketplaceContractIdRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/features",
        "/roadmap",
        "/marketplace/$contractId",
        "/marketplace/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/features": {
      "filePath": "features.tsx"
    },
    "/roadmap": {
      "filePath": "roadmap.tsx"
    },
    "/marketplace/$contractId": {
      "filePath": "marketplace/$contractId.tsx"
    },
    "/marketplace/": {
      "filePath": "marketplace/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
